### PR TITLE
Fixing incomplete links in documentation

### PR DESCRIPTION
**Pull request by sunjay**
I have spent a lot of time in the docs these last few days and one thing that has been bothering me is that some of the links are incomplete/broken in the sense that they render something like `[Webpack][]`. 

It's a small problem, but it only took about 5 minutes to fix so I thought I would just do it.

### CODE REVIEW

**Comment by danielmewes** [comment]
@chipotle

**Comment by sunjay** [comment]
Any updates on this?

**Comment by chipotle** [comment]
The changes were made and deployed last week in 6eabdb7, and I inadvertently left the PR open. Thanks for the fix!

**Comment by sunjay** [comment]
Great! Thanks!

**Pull request closed without merging**
